POST http://localhost:8080/save

###
GET http://localhost:8080


###
POST http://localhost:8080/api/schedules/tasks
Cookie: JSESSIONID=EF8ABB6249CCEE3E18E8CD4F28A5E122
Content-Type: application/json

{
  "title":"",
  "description":"화장실 가기",
  "taskAt": "2021-08-01T11:00:00"
}

###
POST http://localhost:8080/api/schedules/tasks?userId=1
Content-Type: application/json

{
  "title":"test",
  "description":"test111",
  "taskAt": "2021-08-01T11:00:00"
}

###
POST http://localhost:8080/api/schedules/events?userId=1
Content-Type: application/json

{
  "title":"테스트 여행",
  "description":"강원도로",
  "startAt": "2021-09-10T11:00:00",
  "endAt": "2021-09-17T11:00:00",
  "attendeeIds": [2]
}

###
POST http://localhost:8080/api/schedules/events?userId=1
Content-Type: application/json

{
  "title":"스프링 공부",
  "description":"다음시간에는 배치222",
  "startAt": "2021-10-09T14:00:00",
  "endAt": "2021-10-09T15:00:00",
  "attendeeIds": [2]
}


###
POST http://localhost:8080/api/schedules/notifications?userId=1
Content-Type: application/json

{
  "title":"안부차 방문",
  "notifyAt": "2021-08-15T07:00:00",
  "repeatInfo": {
    "interval": {
      "intervalValue" : "1",
      "timeUnit" : "MONTH"
    },
    "times": 10
  }
}

###
GET http://localhost:8080/api/schedules/day?userId=1&date=2021-08-15

###
GET http://localhost:8080/api/schedules/week?userId=1&startOfWeek=2021-08-12

###
GET http://localhost:8080/api/schedules/month?userId=1&yearMonth=2021-09

###
GET http://localhost:8080/api/mail